### ISSUE TITLE
Present licensing options honestly.

### ISSUE THREAD

**Issue by mkcor** [drivendata/cookiecutter-data-science#102]
Hello!

I find that the way licensing options are presented is not honest: https://github.com/drivendata/cookiecutter-data-science/blob/dc146594089677ecc80f85f122ff3ab788eeaf4d/cookiecutter.json#L6

It is not open-ended, so it is basically stating that MIT and BSD (which one?) are the only "open source" licenses out there. There are many more FLOSS licenses to choose from: https://opensource.org/licenses/

I'm happy to prepare a PR to reword all this.

Thank you,
Marianne

**Comment by pjbull** [comment]
This is not about honesty--it's about parsimony.

I don't think it's desirable for us to add and maintain text for every FLOSS license anyone may want to use. Any user is free to replace their `LICENSE` file in an instantiated repository with any license that they want—just like with any project anyone creates, adding a `LICENSE` is up to the developer.

That said, we should support 2 or 3 of the most common licenses. I'd be happy to take a PR that does two things:

 1) Adds a couple of popular licenses to [`cookiecutter.json`] and adds the conditional license text to the [`LICENSE` file in the template](https://github.com/drivendata/cookiecutter-data-science/blob/master/%7B%7B%20cookiecutter.repo_name%20%7D%7D/LICENSE). (Actually, looks like there is a bug where only MIT works now anyway)

 2) Adds a [short section to the documentation](https://github.com/drivendata/cookiecutter-data-science/blob/master/docs/docs/index.md) that says which licenses we support and gives a link to https://opensource.org/licenses/ for anyone interested in exploring other licensing options. 

I think this covers both of the concerns without the burden of maintaining a library of licenses.
