### ISSUE TITLE
MacOS-specific .DS_Store files missing from .gitignore file

### ISSUE THREAD

**Issue by randallrs** [drivendata/cookiecutter-data-science#105]
My colleagues and I were having issues collaborating using this repository template, and noticed that _.DS_Store_ files, which are created during the creation of new folders in MacOS directories, were being tracked by git. This was causing merge issues. I have added this file extension at the end of the _.gitignore_ file.

**Comment by pjbull** [comment]
Great, we'd love a pull request!

**Comment by randallrs** [comment]
Okay, I’ll try to figure out how to do that!
