### ISSUE TITLE
Google Cloud Storage support

### ISSUE THREAD

**Issue by jtascensao** [drivendata/cookiecutter-data-science#120]
Hi guys! I'm wondering if you guys have any plans to add Google Cloud Storage support, in a similar way to what you already do with S3 and AWS.

That would be extremely helpful!

**Comment by dkapitan** [comment]
@jtascensao would be interested in this as well. We work on Google Cloud platform, where every project has a separate:
- Cloud Storage bucket
- Bigquery dataset

I think it is a matter of modifying `cookiecutter.json`, perhaps with some additional logic `if AWS then AWS options` and similiar for `if GCP`.

If anyone can point me in the right direction as to which solution is best (quite new to cookiecutter), I can make a PR for this issue.

**Comment by coleholcomb** [comment]
Where are we with this issue? I'd love to pick it up - I want to adopt cookiecutter for my DS team, but we use GCP in our org.

**Comment by pjbull** [comment]
@coleholcomb It's implemented in v2 (#246), which is coming later this year. The only change is in the Makefile for syncing data from the cloud with `gsutil`:
https://github.com/drivendata/cookiecutter-data-science/blob/1fe968d24e73180a9191152d1573dd870994fcae/%7B%7B%20cookiecutter.repo_name%20%7D%7D/Makefile#L40-L64

**Comment by coleholcomb** [comment]
@pjbull got it, will look forward to v2 then, thanks

**Comment by xzenggit** [comment]
Just curious. When will v2 be released?

**Comment by pjbull** [comment]
@cristianmtr For information on progress on v2, see the [branch tracking the overall work](https://github.com/drivendata/cookiecutter-data-science/pull/246). It also has instructions for how to switch over to using v2 as a beta tester, which would be helpful!

**Comment by jayqi** [comment]
Closing—implemented for V2.
