### ISSUE TITLE
Cookiecutter installation failing at GitHub link pasting stage

### ISSUE THREAD

**Issue by maxpaton** [drivendata/cookiecutter-data-science#121]
I am new to GitHub, so apologies if my question needs work on the structure.

I'm trying to set up a cookiecutter data science project template on my Mac for the first time (recently installed anaconda3 to replace anaconda2, so am using python3). So far, I have successfully installed cookiecutter using pip, but get an error when I type the following in the command line:

`cookiecutter https://github.com/drivendata/cookiecutter-data-science`

The error message begins with:

`Traceback (most recent call last):
  File "/anaconda3/bin/cookiecutter", line 11, in <module>
    sys.exit(main())
  File "/anaconda3/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)`

and ends with:

`subprocess.CalledProcessError: Command '['git', 'clone', 'https://github.com/drivendata/cookiecutter-data-science']' returned non-zero exit status 69.`

In the tutorial I'm following, the correct output is for it to prompt me to create a name for the project, and so on.

Would be grateful to get some feedback on this issue. Thanks!

**Comment by pjbull** [comment]
Doing some Googling, this seems like an issue with `git` on macOS. The suggestion is to open XCode and accept the new license terms and then `git` will work again:
https://dzone.com/articles/fixing-git-failure-code-69-when-opening-sourcetree

Closing for now.

**Comment by maxpaton** [comment]
Thanks a lot, it worked! seems strange since I didn't even have Xcode open or used it in about a year.

Is that a suitable way to present a question on Git? It's my first one...
