### ISSUE TITLE
Advice on handling a lot of raw data files with make

### ISSUE THREAD

**Issue by FabianHertwig** [drivendata/cookiecutter-data-science#125]
Hi,

im currently working on the nyc taxi data. http://www.nyc.gov/html/tlc/html/about/trip_record_data.shtml
For every year, month and one of the three vendors there is a separate csv file with a name with the following pattern: vendor_year_month.csv (eg. yellow_tripdata_2017-01.csv)

Now I want to create make rules that download the files if not yet existing (assume a python file handles the downloading). But I don't want to list every file individually like in this example: 

    yellow_tripdata_2017-01.csv yellow_tripdata_2017-02.csv yellow_tripdata_2017-03.csv ... : download_data.py
        python download_data.py $@

Also I want to declare the files as dependencies for data preparation steps, but again I don't want to list every file individually. 

      prepared_data.csv:  yellow_tripdata_2017-01.csv yellow_tripdata_2017-02.csv yellow_tripdata_2017-03.csv ... 
         python prepare_data.py

Any ideas on how to address these issues?

**Comment by pjbull** [comment]
This is called pattern rules in make:
http://www.gnu.org/software/make/manual/make.html#Pattern-Rules
