### ISSUE TITLE
Provide a PyScaffold extension for a Data Science Project

### ISSUE THREAD

**Issue by FlorianWilhelm** [drivendata/cookiecutter-data-science#126]
Besides Cookiecutter there is also [PyScaffold](https://pyscaffold.org/) which provides a standardised project scaffold for Python. Since version 3.0 PyScaffold also has an extension system and thus it would be possible to provide this cool template also easily for PyScaffold. 

I see several advantages over Cookiecutter:
* Currently `src` seems to be a Python package which is not a good practice if you want to combine several Data Science projects which use this template. One would end up with packages overwriting each others.
* PyScaffold is best for having a standard-compliant Python project scaffold. One could thus focus on providing additional folders and structure within this scaffold. 
* One would have a modern, descriptive way of configuration with the help of `setup.cfg` instead of `setup.py`.
* PyScaffold would also allow to combine a Data Science structure with other extensions for instance having *Tox* support for unit testing, *precommit* for automised tasks etc. 
* PyScaffold allows updating scaffolds which is important in the fast changing world of Python packaging.

**Comment by isms** [comment]
@FlorianWilhelm audreyr/cookiecutter has ~7,400 stars but looks like PyScaffold is quite new.

On the theory that PyScaffold can use cookiecutters and not the other way around, it seems like to keep broadest appeal and usability this should be a separate project? (A project we'd be excited to see happen, but still a separate one.)

Thoughts?

**Comment by FlorianWilhelm** [comment]
@isms Nice, I am pondering about creating a PyScaffold extension that more or less copies the layout and files of `cookiecutter-data-science` if that's okay. I'll let you know when I get to it.

**Comment by isms** [comment]
@FlorianWilhelm yes of course, we'd love to see that. Keep us posted!

**Comment by FlorianWilhelm** [comment]
@isms Took me a while but I finally created a [PyScaffold](https://pyscaffold.org/) extension which copies a lot from `cookiecutter-data-science` under https://github.com/pyscaffold/pyscaffoldext-dsproject. Feedback is highly appreciated.

**Comment by isms** [comment]
@FlorianWilhelm Great stuff, thanks for the update! We would love to hear any input you get or lessons learned.
