### ISSUE TITLE
Add description of virtualenv tools to the documentation

### ISSUE THREAD

**Issue by jbrambleDC** [drivendata/cookiecutter-data-science#14]
I believe Conda can handle what virtualenv + pip is doing in a better way? Should we consider adding this functionality?

**Comment by pjbull** [comment]
Unfortunately, the conda environments are not cross-platform, so we generally prefer pip + virtualenv.  From the [conda docs](http://conda.pydata.org/docs/using/envs.html#create-a-separate-environment):

> NOTE: These explicit spec files are not usually cross platform, and therefore have a comment at the top such as # platform: osx-64 showing the platform where they were created. This platform is the one where this spec file is known to work. On other platforms, the packages specified might not be available or dependencies might be missing for some of the key packages already in the spec.

This template could end up conda/virtualenv agnostic if this issue gets fixed:
https://github.com/conda/conda/issues/1277

Closing for now. 😦

**Comment by isms** [comment]
@jbrambleDC Hey Jordan, thanks for contributing! Just for the record, I almost always use conda environments which are admittedly kind of fiddly to get set up for reasons described pretty well in conda/conda#292 ... that being said it's not too bad.

Here's a hacky workaround I sometimes use:

```bash
# install all binary packages through conda, fail on ones that aren't available
$ cat requirements.txt | while read package; do conda install $package; done
[... blah blah blah, lots of installation]
# now install the rest via the conda env's pip
$ which pip
/home/isaac/anaconda2/envs/test/bin/pip
$ pip install -r requirements.txt 
Requirement already satisfied (use --upgrade to upgrade): click in /home/isaac/anaconda2/envs/test/lib/python2.7/site-packages (from -r requirements.txt (line 1))
[... conda ones are already installed, others get installed now]
```

**Comment by pjbull** [comment]
I think that we may want to give the option to use a `conda env` over `virtualenv`--for example, i just had a project with complex dependencies (e.g., GDAL) and the conda env worked well for that. I also think their env stuff is getting better overall--for example, they now have a path to fall back to `pip`.

Reopening to track adding as an option.

**Comment by isms** [comment]
@jamestwebber I use the template daily and use conda almost exclusively so I don't think there's a conflict.

If we're giving the impression that there is a conflict it'd be helpful to know how in order to fix that.

**Comment by jamestwebber** [comment]
Does it also create a virtualenv inside of a conda environment?

All I've done is just read the doc here: https://drivendata.github.io/cookiecutter-data-science/#build-from-the-environment-up and I got the impression that creating a new project automatically created a new virtualenv.

**Comment by isms** [comment]
To me it just advises the user to use a virtual environment of some kind (of which conda and virtualenv are both implementations) - the only programmatic part people are talking about is some Makefile rules to check whether dependencies are installed and install them if not.

If you were confused, others could be as well. We should explicitly mention conda in the docs.

**Comment by jamestwebber** [comment]
I was reading too fast, I guess. I interpreted the "opinions" section as being baked-in to the generated project template. But now I see you are just recommending the usage of virtualenv.

**Comment by pjbull** [comment]
@jamestwebber @isms Currently the `make create_environment` tries to detect conda and use that if it exists and only fallback to virtualenv:
https://github.com/drivendata/cookiecutter-data-science/blob/master/%7B%7B%20cookiecutter.repo_name%20%7D%7D/Makefile#L58-L73

We should know if (1) that doesn't work and (2) that isn't clear.

**Comment by jamestwebber** [comment]
I haven't tried to use it yet so I can't answer 1, but in terms of 2: there is zero mention of conda on the description page, so it definitely isn't clear! I think it's worth mentioning explicitly.

**Comment by pjbull** [comment]
Updated issue name, would love a PR!

**Comment by isms** [comment]
Closing as inactive and outdated by current WIP.
