### ISSUE TITLE
Apostrophes in project description break Sphinx template

### ISSUE THREAD

**Issue by OleMussmann** [drivendata/cookiecutter-data-science#142]
The project description string is inserted into the Sphinx template `conf.py` without further checks:

`'{{ cookiecutter.description }}'`

If there are apostrophes in the string, the template will break:

`'description's with apostophe's are evil'`

The same will hold true for other user input strings, such as project names, etc.

**Comment by jayqi** [comment]
Fixed by #313 for V2
