### ISSUE TITLE
Place to keep custom functions

### ISSUE THREAD

**Issue by karun-r** [drivendata/cookiecutter-data-science#144]
If my project requires me to build some custom classes, what is the best practice to do so if I am using this template ?

In my use case, I have to do some repeated checks on the data in multiple phases of the project. To be specific, I have a function in the make_features.py that takes in a date column and creates few additional columns in my dataset. So here, I am planning to introduce couple of lines if the column mentioned by the user as the date column is actually a date column or not and throw an appropriate error message if it's not. 

I can very well do this during the data preparation phase in make_data.py but I am just thinking if there is any common place where I should keep some utility functions that would be used through out the project i.e. in Feature creating phase, EDA phase, model building phase etc. 

Any thoughts ?

**Comment by hackalog** [comment]
I use `src/utils.py` for generic utility functions. I also have things like `src/data/utils.py`, `src/model/utils.py`, and so on. See, for example, https://github.com/hackalog/bus_number

**Comment by isms** [comment]
Anywhere you like in `src/` makes sense - the filenames in there are just placeholders!
