### ISSUE TITLE
Unit testing

### ISSUE THREAD

**Issue by itobysq** [drivendata/cookiecutter-data-science#145]
Thanks for putting this together, it's a very nice layout. I appreciate the emphasis in the docs about reproducibility and was surprised that there was not a tests directory. 

Maybe it's just me but I like putting in unit tests to make sure that if I make a code change for optimization in one place, that it does not accidentally affect my analysis results. I would be happy to add the /tests directory and make the changes in setup.py if you think this is a worthwhile change.

**Comment by isms** [comment]
@itobysq A suite of pytest tests would be a very welcome addition.

**Comment by hackalog** [comment]
At present, I keep tests in the module dir itself; e.g.  something like this in the makefile:
```
## Run all Unit Tests
test:
     cd src && pytest --doctest-modules --verbose --cov
```

My tests tend to be split between pytest, hypothesis, and doctests. YMMV

**Comment by isms** [comment]
Very open to hearing more about what parts should be tested and seeing patches but closing for now.
