### ISSUE TITLE
unable to setup the project structure or download

### ISSUE THREAD

**Issue by zainmdm** [drivendata/cookiecutter-data-science#152]
I am unable to setup this project with after installed using conda 2 and python 2.7

after running the below, its just returning back to the prompt, please suggest
$ cookiecutter https://github.com/drivendata/cookiecutter-data-science

zainmdm@DESKTOP-D0AN22H MINGW64 /d/zain_python/gitcode (master)
$ echo $?
1

**Comment by pjbull** [comment]
@zainmdm I don't reproduce this bug with Python 2.7.

```
 $ python -c "import sys; print sys.version"
2.7.15 |Anaconda, Inc.| (default, Nov 13 2018, 17:07:45)
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]
 $ cookiecutter https://github.com/drivendata/cookiecutter-data-science
You've downloaded /Users/bull/.cookiecutters/cookiecutter-data-science before. Is it okay to delete and re-download it? [yes]:
```

Do other `cookiecutter` templates work for you: https://github.com/audreyr/cookiecutter#python

**Comment by zainmdm** [comment]
Excellent its working now. thanks a lot for the great help
