### ISSUE TITLE
pip freeze loses structure from original requirements.txt

### ISSUE THREAD

**Issue by brylie** [drivendata/cookiecutter-data-science#155]
The original requirements.txt file contains 

```
# local package
-e .
```

When running `pip freeze > requirements.txt` the above line is lost, and may be easy to overlook when committing the new requirements.txt file.

Is the `-e .` important for the project to work 'correctly', in the context of a reproducible data science workflow? If so, is there another way to define the `-e .` flag, so that it won't be accidentally lost when freezing additional project requirements?

**Comment by pjbull** [comment]
Closing since nothing we can do about this at the moment, it is a bug in `pip freeze`.

This should work once pip `19.0` is out:
https://github.com/pypa/pip/issues/5031

**Comment by brylie** [comment]
Good to know there is an upstream issue. I am pretty novice to all of this. Thanks!
