### ISSUE TITLE
integration with mlflows and snakemake

### ISSUE THREAD

**Issue by chanansh** [drivendata/cookiecutter-data-science#156]
I think that logging via mlfows and make via snakemake can enhance this project

**Comment by isms** [comment]
Copying a reply from #158:

Our approach to integrations is generally to leave that up to the user.

Some questions that might be helpful to hear more about:

* If somebody intending to use DVC can just dvc init in their project then what would an integration look like?
* And if they don't use or know about DVC is the purpose of the integration to push them to use it or educate about its merits? How might this affect the user experience?
