### ISSUE TITLE
Intended use for production?

### ISSUE THREAD

**Issue by set92** [drivendata/cookiecutter-data-science#172]
I was trying to use this in my company, but in general this seems more like for researching purposes than using it in production environments. Or is /src the folder intended for productivizing the code? 

What is the intended way to use it? Doing the Analysis/EDA, first version of the pipeline in notebooks and then when you are going to production pass it to .py in /src? But with the folder of visualization there I think that folder is more intended to scripts of development.

Right now my boss bought using it but with another folder of production which has all the files that you will send to a group of developers to use it in their own product.

**Comment by isms** [comment]
Primarily this structure is designed for research. But that doesn't mean you couldn't put things in `src/` into production.

When we have done so, there's usually a Docker setup that will `COPY src/` from the working directory to `/project` within the container so none of the other things are present (unless you need them and specifically want to insert them into the container).
