### ISSUE TITLE
Revision control or not?

### ISSUE THREAD

**Issue by r0f1** [drivendata/cookiecutter-data-science#175]
Hi, 
I have more of a general question. Which directories do you put under revision control? Putting only the `src` folder under revision control seems too little. Putting all folders under revision control seems too much, since for example the `model` folder can get quite big. 
Any ideas?

**Comment by jamesmyatt** [comment]
Default should be everything that's not .gitignore'd.

If you don't put your trained models in VCS, which might be valid if they're large, then you need some other strategy to version control them.
