### ISSUE TITLE
Add explantion of using `.env` to docs

### ISSUE THREAD

**Issue by pjbull** [drivendata/cookiecutter-data-science#18]
- E.g., deployment secrets, access keys, SQL connection strings

**Comment by isms** [comment]
@pjbull just added explanation [here](http://drivendata.github.io/cookiecutter-data-science/#keep-secrets-and-configuration-out-of-version-control) via 873cfd6 - thoughts?

**Comment by pjbull** [comment]
👏 👏 👏 

The one thought is that notebooks don't have `__file__` defined so we should try to make a code snippet that plays nicely with both.

<img width="1050" alt="screen shot 2016-04-29 at 3 13 04 pm" src="https://cloud.githubusercontent.com/assets/1799186/14928355/01ad03fe-0e1d-11e6-9ded-9fc2cb36c869.png">

**Comment by isms** [comment]
Pull request added: https://github.com/drivendata/cookiecutter-data-science/pull/22
![](https://cloud.githubusercontent.com/assets/1284973/14932008/74c635ba-0e3e-11e6-9d9e-5219219fcdfc.png)
