### ISSUE TITLE
Link to "Edit in Github" still broken on project homepage

### ISSUE THREAD

**Issue by BrunoGomesCoelho** [drivendata/cookiecutter-data-science#181]
This is a continuation of issue #146. The link seems to still be broken.

# Steps to Repro:

- Go to the project homepage http://drivendata.github.io/cookiecutter-data-science/
- In the top right there is a button "Edit on Github" that links to this page: https://github.com/drivendata/cookiecutter-data-science/edit/master/docs/index.md
- Click on that link

# What I got

The link sends me to a 404 "not found" error page on github.

# What I wanted

What I expected was it would send me to some page on GitHub.

# Possible fix

I imagine maybe the docs is built from the gh-pages branch and not the master branch - if that's the case we would need to edit [this line spefically](https://github.com/drivendata/cookiecutter-data-science/blob/9e01bf8d09c6dd65f435acc50444971b771ebfe4/index.html#L74) on the gh-pages branch.

**Comment by isms** [comment]
Working right now.
