### ISSUE TITLE
Video of example in documentation is displaying error.

### ISSUE THREAD

**Issue by stevans** [drivendata/cookiecutter-data-science#197]
In the "Example" section of the documentation, the video showing an example of running cookiecutter is no longer available. In place of the video is the following text:

"This recording has been archived
All unclaimed recordings (the ones not linked to any user account) are automatically archived 7 days after upload."

In addition to recovering the video, perhaps displaying a set of screenshots would be a simple redundancy.

**Comment by pjbull** [comment]
Added to the new CLI refactor, but as a stop gap it would be great if you could record one and add it! Looks like terminalizer is popular for making that kind of gif these days:
https://github.com/faressoft/terminalizer

**Comment by bitnot** [comment]
Looks like it [has been fixed](https://github.com/drivendata/cookiecutter-data-science/commit/997a9db06d5a8f80779a6abec7ba4963419b431e#diff-7dd3ba15306fb8ca0c3fa4a2e10b4d3b708c3a338bc2c4a028b4e1d0e565dc88) but has not been re-deployed since.

**Comment by pjbull** [comment]
Fixed and deployed
