### ISSUE TITLE
tox link in README.md seems to be out of date

### ISSUE THREAD

**Issue by ColinLeongUDRI** [drivendata/cookiecutter-data-science#209]
https://github.com/drivendata/cookiecutter-data-science/blob/master/README.md#the-resulting-directory-structure contains this line: 

```
└── tox.ini            <- tox file with settings for running tox; see tox.testrun.org
```

However, tox.testrun.org doesn't seem to actually have to do with tox. Perhaps the link is outdated. 

Suggestion: use https://tox.readthedocs.io/ instead.

**Comment by natravedrova** [comment]
Seems to be fixed in 78e001f742f8253c88e6edb62ea35ebfa8939f18
