### ISSUE TITLE
Jupyter notebooks as main component?

### ISSUE THREAD

**Issue by BjornFJohansson** [drivendata/cookiecutter-data-science#222]
Hi, I make small data science project where the code is exclusively
Jupyter notebooks. These need to be in the top folder in order to access for example 
data files and can AFAIK not access files in folders above.

Is there an alternative version of this where all data is below the notebooks folder? Or can this be solved in some other way?
I like the idea of using some kind of standard.

**Comment by pjbull** [comment]
Notebooks can access any paths the same way any Python program can. For example:

```python
from pathlib import Path

df = pd.read_csv(Path("../data/my_data.csv"))
```
