### ISSUE TITLE
Project still alive?

### ISSUE THREAD

**Issue by amin-nejad** [drivendata/cookiecutter-data-science#233]
Hi, I'm researching different options for this kind of thing and I came across this repo which seems great.

I'm just wondering if this is still actively maintained? Are there any plans to support Python 3.6-3.9?

Thanks!

**Comment by pjbull** [comment]
Yep, the version numbers in the README are minimums. Just added a `+` to make that clear.

**Comment by amin-nejad** [comment]
Thank you!
