### ISSUE TITLE
Test suite

### ISSUE THREAD

**Issue by pjbull** [drivendata/cookiecutter-data-science#24]
We should setup a simple test suite. Mostly focused on config testing, I would guess:
- CI Server that runs tests on multiple OSes: osx/linux/windows
- Tox for multiple Python versions

**Comment by pjbull** [comment]
Did a little research on CI options. Looks like [Travis](https://docs.travis-ci.com/user/multi-os/) supports osx and linux and is free for OSS. [Appveyor](http://www.appveyor.com/pricing) supports Windows and is also free for OSS.  Seems not uncommon to run both to get coverage on Windows, OSX, Linux (e.g., that seems to be [what cookiecutter does](https://github.com/audreyr/cookiecutter)).

**Comment by pjbull** [comment]
e385aff019adf68802d68af56fb9d97c26148b32 Adds basic test support

**Comment by isms** [comment]
Closing as vague and outdated.
