### ISSUE TITLE
Quotes should be escaped on project init

### ISSUE THREAD

**Issue by LilianBoulard** [drivendata/cookiecutter-data-science#248]
Hello

While creating a new project, I entered a description with a single quote like "Project for our Bachelor's Degree".
As I look in the `setup.py` file, this quote is not escaped, resulting in a syntax error:

![image](https://user-images.githubusercontent.com/33222654/115109855-9636d580-9f78-11eb-8fe9-8b1e3a7d73f2.png)

I assume the same issue would occur if I were to enter a quote inside other fields, like `author`, but I didn't try it out.

Cheers

**Comment by pjbull** [comment]
Thanks for reporting!

Definitely seems worth fixing for a number of fields where we might have quote characters. We'd take a PR that fixes this for `description`, `author`, and `project_name`.

Looks like there's a suggestion on the main cookiecutter repo for a fix:
https://github.com/cookiecutter/cookiecutter/issues/936#issuecomment-301189214

**Comment by jayqi** [comment]
Fixed by #313 for V2
