### ISSUE TITLE
Access denied: cookiecutter https://github.com/drivendata/cookiecutter-data-science

### ISSUE THREAD

**Issue by vandanafs** [drivendata/cookiecutter-data-science#266]
When I tried to clone the repository using cookiecutter I am getting access denied.I have already installed 
1.pip install cookiecutter 2.conda install cookiecutter.
Please find the attached screenshot.
![image](https://user-images.githubusercontent.com/60112122/161353802-ca754600-4625-45d4-bb48-1f708e581b9a.png)

**Comment by vandanafs** [comment]
Hi @pjbull  Could you kindly  look into above issue.

**Comment by pjbull** [comment]
@vandanafs It appears that you don't have access to the `cookiecutter` executable for some reason. This is a problem with your machine's configuration of your Python installation, and is not a problem that we can fix so I'll close this issue.

It sounds like you're using conda. In that case, I'd recommend creating and using a new environment from scratch and using that to manage your python packages:
https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html

Beyond that, we can't provide additional support on this issue.

(Also, please don't @ maintainers on support requests, thanks!)
