### ISSUE TITLE
Remove --recursive from s3 sync commands in Makefile

### ISSUE THREAD

**Issue by mrbell** [drivendata/cookiecutter-data-science#28]
At least as of AWS CLI v 1.10.32 the `aws s3 sync` command does not have a `--recursive` flag. As such, running the `sync_data_to_s3` or `sync_data_from_s3` make rules throws the error

> Unknown options: --recursive
> make: *** [sync_data_to_s3] Error 255

The sync operation is recursive by default [see the aws cli docs](http://docs.aws.amazon.com/cli/latest/reference/s3/sync.html). 

The `--recursive` flag should be removed from the default Makefile.

**Comment by pjbull** [comment]
Ah! Nice catch. Happy to accept a PR for this.

**Comment by mrbell** [comment]
Just submitted a PR.
