### ISSUE TITLE
pip 2020 resolver no longer valid

### ISSUE THREAD

**Issue by chrisjkuch** [drivendata/cookiecutter-data-science#294]
Attempting to run a build on the latest `v2` branch yields the following:

```
option --use-feature: invalid choice: '2020-resolver' (choose from 'fast-deps', 'truststore', 'no-binary-enable-wheel-cache')
```

Pip 22.3 [removes](https://pip.pypa.io/en/stable/news/#v22-3) that option since this resolver is now default.

**Comment by jayqi** [comment]
I don't think we have this anywhere anymore.
