### ISSUE TITLE
Update the python-dotenv requirement

### ISSUE THREAD

**Issue by tdeboissiere** [drivendata/cookiecutter-data-science#30]
I have encountered a bug the the dotenv module (not finding the .env file with `load_dotenv(find_dotenv())`). This was fixed in [this issue](https://github.com/theskumar/python-dotenv/issues/24) by installing the latest master.

So it may be worth upgrading the requirements file with:

click
Sphinx
coverage
awscli
flake8
https://github.com/theskumar/python-dotenv/archive/master.zip

**Comment by isms** [comment]
@tdeboissiere thanks for opening this issue - looks like that `find_dotenv` bug is on me :blush: - as you point out, @theskumar already fixed it the master branch, so as soon as he creates a new release we'll just bump the version. He works quickly so it shouldn't be long!

**Comment by isms** [comment]
@tdeboissiere all set thanks to some fast [work](https://github.com/theskumar/python-dotenv/issues/24#issuecomment-222299040) by @theskumar - thanks again!
