### ISSUE TITLE
Add documentation about major changes between V1 and V2

### ISSUE THREAD

**Issue by jayqi** [drivendata/cookiecutter-data-science#318]
- [x] add documentation for new installation (pip install cookiecutter-data-science) and new initiation (ccds <path to repo>)
- [x] add table of options with links to the project documentation in our docs
- [x] ~add documentation for passing partial configs and only getting asked the unanswered questions!~ deferred, see #325 in 2.1

**Comment by pjbull** [comment]
Last item in PR #350
