### ISSUE TITLE
Add Python 3.12 support

### ISSUE THREAD

**Issue by chrisjkuch** [drivendata/cookiecutter-data-science#328]
- [x] Update tests
- [x] Update pyproject.toml

**Comment by chrisjkuch** [comment]
@pjbull @jayqi The conda build from an environment file in Python 3.12 is failing because there are conflicts between packages in the defaults channel for 3.12.

I see a few potential ways to address this:
* Add conda-forge as a channel provider for conda environment.yml setups, either for all python versions or just for 3.12
* Wait to add 3.12 support until defaults support for these packages is better

There may be other ways to address, input / thoughts welcome.

**Comment by pjbull** [comment]
> Wait to add 3.12 support until defaults support for these packages is better

I'd vote for this for the time being. Hard to imagine that the default unpinned versions of the core DS packages continue to generate conflicts for any extended period of time.

**Comment by chrisjkuch** [comment]
Sounds good, moved to milestone 2.1

**Comment by chrisjkuch** [comment]
Closed by #329
