### ISSUE TITLE
Click seems to be flawed on Python 3 - Consider using docopt

### ISSUE THREAD

**Issue by ohenrik** [drivendata/cookiecutter-data-science#34]
I don't know much about click or docopt yet, so don't shoot me if i'm lost here. Click seems to be handling Python 3 a bit badly. Should we consider switching to http://docopt.org/ ?

By the way i manage to get Click working by running, `export LC_ALL=no_NO.utf-8` and `export LANG=no_NO.utf-8`. But It seems like there might be more issues witch Click and Python 3:
http://click.pocoo.org/6/python3/

**Comment by isms** [comment]
@ohenrik Thanks for raising this. I just checked and it's currently only used in our `make_dataset.py` stub, so it should be easily swappable with docopt.

@pjbull Thoughts on making "use click" an option? It adds a bit of complexity - we could also just start a Python 2/3 section in the README noting things like this; there are sure to be others.

**Comment by xguse** [comment]
I for one MUCH prefer click to docopt.

**Comment by isms** [comment]
@xguse Thanks for weighing in on this :+1:

**Comment by pjbull** [comment]
@ohenrik @isms I think that if there were to be a fix here, it is to rollback from `click` to vanilla `argparse` and reduce the number of packages we have opinions about. But, in my mind, the locale problem in Python 3 isn't a strong enough reason to ditch `click` given how pleasant the API is for getting things up and running quickly.

I'd say we leave this issue for a little bit to see if others have a problem with `click`, and if not we can scrub the issue. :+1:

**Comment by isms** [comment]
Looks like others don't feel strongly about this judging by the comment history — closing for now, but thanks @ohenrik for flagging this.
