### ISSUE TITLE
Add default config file to src/

### ISSUE THREAD

**Issue by ohenrik** [drivendata/cookiecutter-data-science#37]
Hi

Should we add a `src/config.py` or `src/settings.py` file? I believe this would make it easier to get paths to folders etc. in make_data.py for example. 

``` python
# src/config.py
""" Storing config variables and other settings"""
from os.path import join, dirname, os, abspath
from dotenv import load_dotenv
import inspect

dotenv_path = join(dirname(__file__), '../.env')
load_dotenv(dotenv_path)

class ParamConfig:
    """Config variables for the project"""
    def __init__(self):
        self.kaggle_username = os.environ.get("KAGGLE_USERNAME")
        self.kaggle_password = os.environ.get("KAGGLE_PASSWORD")
        self.config_dir = dirname(abspath(inspect.getfile(inspect.currentframe())))
        self.root_dir = dirname(self.config_dir)

        # Data directories
        self.data_dir = os.path.join(self.root_dir, 'data')
        self.raw_data_dir = os.path.join(self.data_dir, 'raw')
        self.processed_data_dir = os.path.join(self.data_dir, 'processed')

config = ParamConfig()
```

I can then import the config variable like so:

``` python
# Selective excerpt from src/data/make_data.py as an example 
from src.settings import config 

def main(output_zip=False):
    """Create data!"""
    logger = logging.getLogger(__name__)
    logger.info('making final data set from raw data')

    # compression = 'gzip' if output_zip is True else

    # Read raw data (auto unzipping files!)
    train_sales = pd.read_csv(path.join(config.raw_data_dir, 'train.csv.zip'))
    test_sales = pd.read_csv(path.join(config.raw_data_dir, 'test.csv.zip'))
    stores = pd.read_csv(path.join(config.raw_data_dir, 'store.csv.zip'),
                         dtype={'CompetitionOpenSinceYear': str,
                                'CompetitionOpenSinceMonth': str,
                                'Promo2SinceWeek': str,
                                'Promo2SinceYear': str,})

```

However note that importing settings in this way also requires me to change the make file from this:

```
data:
    python -m src/data/make_dataset.py

```

to this:

```
data:
    python -m src.data.make_dataset
```

I'm not sure if this has any downsides to it. An alternative is also to add the src and/or settings file to the python path.

I'm still learning both Python and Data Science so please bear with me if what I'm suggesting or my code is Silly :)

**Comment by ohenrik** [comment]
Ups! Sorry i can see that this is what you are using the dotenv file fore. If i understand the example at the top of the file correctly:
https://github.com/drivendata/cookiecutter-data-science/blob/master/%7B%7B%20cookiecutter.repo_name%20%7D%7D/.env#L5

**Comment by pjbull** [comment]
Hey @ohenrik thanks for the thoughts. Generally, we want anything that varies from machine to machine to be stored in the environment. Check out the 12-factor app's [section on configuration](http://12factor.net/config) for more reasons why.

Projects with a large number of settings do grow into having a separate importable settings or config module (e.g., a `django` application). My inclination is to keep things simple by default and not roll our own settings module that would need development/support/documentation at the base level of the cookiecutter.

Happy to consider if there are really compelling use cases for needing a `config.py` as a default, but I think environment variables will cover most of them.

**Comment by epogrebnyak** [comment]
Hope the question fits here... what about a helper module or `src/settings.py` to access data folder?

In src/data/make_data.py you have:

https://github.com/drivendata/cookiecutter-data-science/blob/be7f8d76b2c542a1f355046d132d6fd39b0b2a6d/%7B%7B%20cookiecutter.repo_name%20%7D%7D/src/data/make_dataset.py#L23-L24

Myself I use something like below to locate the repo root folder:

https://github.com/WLM1ke/PortfolioOptimizer/blob/57f381158a2a7b93bd7925272929f7262016d9b7/src/portfolio/settings.py#L3-L5


Once the data directory structure is there template, maybe path to it should be in `src/settings.py` too? For me it is seems a good convenience feature.

**Comment by isms** [comment]
Closing as possible in the future but based on participation in this `question` issue it's not a commonly desired feature (or is easily slotted in on a per-project basis).
