### ISSUE TITLE
make src home to not just Python code

### ISSUE THREAD

**Issue by xguse** [drivendata/cookiecutter-data-science#42]
I routinely have to use R code in my pipeline rules/targets. I propose changing the `src` organization as follows:

Change the current:

```
src
├── data
│   └── make_dataset.py
├── features
│   └── build_features.py
├── __init__.py
├── models
│   ├── predict_model.py
│   └── train_model.py
└── visualization
    └── visualize.py
```

to something akin to this:

```
src
├── python
│   ├── data
│   │   ├── __init__.py
│   │   └── make_dataset.py
│   ├── features
│   │   ├── build_features.py
│   │   └── __init__.py
│   ├── __init__.py
│   ├── models
│   │   ├── __init__.py
│   │   ├── predict_model.py
│   │   └── train_model.py
│   ├── rules
│   │   ├── __init__.py
│   │   └── template_python_script.py
│   └── visualization
│       ├── __init__.py
│       └── visualize.py
└── R
    └── rules
        └── template_R_script.R
```

Thoughts?

**Comment by isms** [comment]
Those folders and scripts in `src/` right now are just some examples and stubs, more for inspiration than to set a standard structure. It seems like this folder is going to be so different depending on project-specific goals, people are going to have to choose what they need based on each project — from the simple (a couple scripts directly in `src/`) to the complex (multiple languages/apps/subfolders).

That being said, I really like how you've organized that for multiple languages. Two thoughts:

* @pjbull and I have been talking about how we can feature examples of the cookiecutter data science template being used in different ways, so if you have an open-sourceable project we'd love to point to it.

* Maybe we could add "cookbook"/"common patterns"/"example" section or page to the documentation  highlighting ideas like this? It would be a great middle ground between changing the base structure for everyone and letting these good ideas fall through the cracks.

**Comment by xguse** [comment]
Ahh thats great.  

I am basically merging my own (__nascent__) cookiecutter for snakemake-based analysis pipelines into my fork of this project and I was worried about bumping up against this (http://drivendata.github.io/cookiecutter-data-science/#be-conservative-in-changing-the-default-folder-structure).  But now that I think about it some more, I suppose that what you mean by "changing the folder structure for all projects" would concern things like pull requests to the upstream repo.

_Regarding pointing to my project:_ That would be great.  As soon as I work out the kinks that will surely result from merging my old system into this general framework, I will shoot you guys a line.

_How to feature examples:_ I think adding a section in the `readme.md` would allow folks to add their "interesting use-case" and submit a PR.  That way you guys don't have to go out LOOKING for them but still have final say over what gets added.  I think that is how the crew over at https://github.com/audreyr/cookiecutter do it, anyway.
