### ISSUE TITLE
Add package list that populates `requirements.txt` to the workflow

### ISSUE THREAD

**Issue by pjbull** [drivendata/cookiecutter-data-science#5]
This issue is for adding a user editable list during project creation that will allow a user to name packages. E.g.:
```
...
List packages to include [default: pandas,numpy,scikit-learn]:  
...
```

**Comment by brylie** [comment]
@pjbull could you please clarify this issue with a description of the problem? I may be reporting a similar issue.

**Comment by pjbull** [comment]
@brylie Thanks for ping here, added clarification! (Not related to the issue you mentioned)

**Comment by jayqi** [comment]
Closing—implemented for V2.
