### ISSUE TITLE
Make default repo_name lowercase

### ISSUE THREAD

**Issue by mattayes** [drivendata/cookiecutter-data-science#52]
Right now the default `repo_name` is simply the provided `project_name`, replacing spaces with underscores: `"repo_name": "{{ cookiecutter.project_name|replace(' ', '_') }}"`.

It would be nice if the default also converted the `project_name` to lowercase as well: `{{ cookiecutter.project_name.lower().replace(' ', '_') }}`.

Thoughts?

**Comment by isms** [comment]
Good idea :+1:
