### ISSUE TITLE
Rename IPython NB to Jupyter NB

### ISSUE THREAD

**Issue by mattayes** [drivendata/cookiecutter-data-science#53]
Alright, this is SUPER nitpicky. Jupyter Notebooks is the new name for IPython Notebooks. The comment above `.ipynb_checkpoints/` in the `.gitignore` should be changed from `# IPython NB Checkpoints` to `Jupyter NB Checkpoints`.

I'm going to submit a PR to make the change (like I said, really nitpicky).

**Comment by isms** [comment]
Nitpicky is good! Will merge as soon as you submit PR.
