### ISSUE TITLE
Add hooks for virtualenvs

### ISSUE THREAD

**Issue by pjbull** [drivendata/cookiecutter-data-science#6]
Allow creating a virtualenv for the project through hooks:
http://cookiecutter.readthedocs.org/en/latest/advanced_usage.html#using-pre-post-generate-hooks-0-7-0

**Comment by GilJ** [comment]
To add to this, I think it might be useful if the virtualenv has an editable version installed of the code in the src directory.

**Comment by jayqi** [comment]
Closing—implemented for V2.
