### ISSUE TITLE
Minor issue with self documenting make

### ISSUE THREAD

**Issue by isms** [drivendata/cookiecutter-data-science#67]
In a fresh project, running `make` (Ubuntu) gives me:

```
$ make
/bin/sh: 1: test: Linux: unexpected operator
Available rules:

clean               Delete all compiled Python files 
create_environment  Set up python interpreter environment 
data                Make Dataset 
lint                Lint using flake8 
requirements        Install Python Dependencies 
sync_data_from_s3   Download Data from S3 
sync_data_to_s3     Upload Data to S3 
test_environment    Test python environment is setup correctly
```

It looks like a problem with the invocation of `test` (my `uname` is `Linux`).

Seems like this comes from the very [last line](https://github.com/drivendata/cookiecutter-data-science/blob/master/%7B%7B%20cookiecutter.repo_name%20%7D%7D/Makefile#L133) of the self documenting rule:

```
	| more $(shell test $(shell uname) == Darwin && echo '--no-init --raw-control-chars')
```

Changing the `==` to `=` seems to get rid of the `/bin/sh: 1: test: Linux: unexpected operator`.

@pjbull Can you see if this works on OS X?

**Comment by pjbull** [comment]
That change also works on OSX :+1:
