### ISSUE TITLE
Make on Windows link not working

### ISSUE THREAD

**Issue by isms** [drivendata/cookiecutter-data-science#68]
Thanks to @epogrebnyak for reporting.

**Comment by NapsterInBlue** [comment]
Hello from a year later! lol

Any idea what this link was *supposed* to be?

**Comment by pjbull** [comment]
Hm, not sure, but there are a fair number of options now. 

I'm not on Windows, so would appreciate testing/recommendations/PR. I think the main options are:

 - [Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/install-win10)
 - [Cygwin](https://www.cygwin.com/)
 - [MinGW](http://www.mingw.org/)

That said, I'm not sure that I'd recommend any of those options where you expect a lot of Windows developers. Either a batch script, powershell, or a Python-based DAG runner (snakemake, luigi, airflow) is probably less headache.

**Comment by NapsterInBlue** [comment]
Hey, thanks for such a quick response!

Trying to figure out/proliferate Python best practices at my org of mostly Windows users. I'm currently using Git bash from the [Git for Windows suite](https://gitforwindows.org/) (which uses MinGW internally) and then, regrettably, steering folks [here](https://gist.github.com/evanwill/0207876c3243bbb6863e65ec5dc3f058#make) if they want to add `make`.

So emphasis on "headache" in your last sentence, haha

I'll give cygwin a shot today, though. Thanks again!

**Comment by pjbull** [comment]
We've been thinking about experimenting with [`snakemake`](https://snakemake.readthedocs.io/en/stable/), which is Python-based so should run without additional installation pain. Would be very curious to look at your snakemake file for inspiration if you go that way!

**Comment by NapsterInBlue** [comment]
Hey again.

So cygwin comes even barer than Git Bash, out of the box. You can, however, specify all kinds of packages at the time of install, including `make`. Problem here, though, is the size of that scrollbar.

![image](https://user-images.githubusercontent.com/3505365/43650185-2118a402-970d-11e8-9c44-e2460b4dabef.png)

So unless you know what you're looking for, it's pretty intimidating.

### Couple solutions here:

- You can always rerun the `setup-XXX.exe` to upgrade/add any packages you find out later that you want, which seems pretty painless.
- It's possible to [just script away your entire setup](https://stackoverflow.com/questions/745275/can-i-script-a-cygwin-install-to-include-certain-packages) with a `.bat` file, once you figure out what works for you.

But it'd probably take awhile to figure needle/haystack all of the good stuff from everything that's available. What I've got now will suffice, I think.

**Comment by NapsterInBlue** [comment]
And looking at `snakemake`, I like the idea, but unless it can natively run my existing makefiles, it feels [a bit like this](https://xkcd.com/927/).

**Comment by wolfhoundjesse** [comment]
@NapsterInBlue What if you were to `choco install make --source=cygwin` and avoid the huge list? Having a fifteenth package manager on my machine doesn't feel great.

**Comment by pjbull** [comment]
Fixed in #355
