### ISSUE TITLE
Clarify what DAG means in docs

### ISSUE THREAD

**Issue by isms** [drivendata/cookiecutter-data-science#69]
Thanks to @epogrebnyak for reporting.

**Comment by arturomoncadatorres** [comment]
In the context of the documentation, I believe it means [Directed Acyclic Graph](https://en.wikipedia.org/wiki/Directed_acyclic_graph). I agree it would be nice to have it explicitly defined

**Comment by arturomoncadatorres** [comment]
I guess that after [PR 243](https://github.com/drivendata/cookiecutter-data-science/pull/243), this issue could be closed, right @isms?
