### ISSUE TITLE
Swap out Sphinx for mkdocs

### ISSUE THREAD

**Issue by pjbull** [drivendata/cookiecutter-data-science#7]
Sphinx is really good for projects where documentation lives in docstrings in the code. Mkdocs is easier to write from scratch, style, and deploy.

Also, I've got a preference for writing markdown over RST

**Comment by isms** [comment]
Agreed (especially on MD vs rST :sweat:), but per our discussion yesterday I think there might be two separate use cases - not sure Mkdocs actually replaces Sphinx for code documentation. (Some limited discussion here: mkdocs/mkdocs#20)

As a counterargument, do we really expect people to write full-on docstrings in most data science code? Most of the time I'd probably choose lightweight set of doc pages like (approach, dev setup, deployment) over heavy duty Sphinx docs.

My vote is actually to allow either as a cookiecutter option.

**Comment by caduvieira** [comment]
Mkdocs do not generate PDF from MD. Sphinx can generate PDF from MD  http://www.sphinx-doc.org/en/stable/markdown.html
