### ISSUE TITLE
How to add s3 bucket manually after project creation?

### ISSUE THREAD

**Issue by Sarickshah** [drivendata/cookiecutter-data-science#74]
Do I just manually type it in here in the makefile? : BUCKET = {{ cookiecutter.s3_bucket }}

**Comment by pjbull** [comment]
Yes, this is the only place it is used:
https://github.com/drivendata/cookiecutter-data-science/blob/master/%7B%7B%20cookiecutter.repo_name%20%7D%7D/Makefile#L8
