### ISSUE TITLE
Importing modules/packages from src into notebooks

### ISSUE THREAD

**Issue by drorata** [drivendata/cookiecutter-data-science#76]
I am inspired by this tool (but haven't used it yet). I am wondering, how do you import code from `./src` into a notebook located in `./notebooks`?

**Comment by pjbull** [comment]
There's a snippet for doing this in the docs here:
https://drivendata.github.io/cookiecutter-data-science/#notebooks-are-for-exploration-and-communication

Note it uses`%aimport` with the assumption things in `src` are being actively developed. If not, just a normal import works as well.

Enjoy!
