### ISSUE TITLE
Why does `make data` trigger `make requirements` on each run?

### ISSUE THREAD

**Issue by KPLauritzen** [drivendata/cookiecutter-data-science#77]
Maybe I'm just not understanding Make, but I would think that after running `make requirements` the first time, it would only trigger if there is a change to `test_environment.py` or `requirements.txt`. 

But every time I run `make data` I get pip trying to install all my requirements. 
Is that on purpose?

**Comment by pjbull** [comment]
Hm, does adding a dependency on `requirements.txt` fix that for you?

E.g., in the Makefile change the line that is `requirements:` to `requirements: requirements.txt`? (You may also need to remove `requirements` from the commands after `.PHONY`)

**Comment by KPLauritzen** [comment]
No, that does not seem to help. 
Showing the essential parts of the Makefile:
```
.PHONY: clean lint sync_data_to_s3 sync_data_from_s3 sync_models_to_s3 sync_models_from_s3
## Install Python Dependencies
requirements: requirements.txt
	pip install -r requirements.txt

## Make Dataset
data: requirements
	echo Making data
```
It still runs `pip install ...` on every `make data`. 
I realize that this is mostly a Make issue, but I was just curious if this was the intended behaviour.

**Comment by pjbull** [comment]
I don't think there's a clean way to do this using `make` without simply removing the dependency. Sorry.
