### ISSUE TITLE
Add option to choose different data storage back ends

### ISSUE THREAD

**Issue by pjbull** [drivendata/cookiecutter-data-science#8]
- S3 (get AWS settings)
- Git Large File Storage
- Git Annex
- dat

**Comment by isms** [comment]
Possibly a good reference here - when starting a new static site project with [Pelican](https://github.com/getpelican/pelican)'s quickstart tool, it asks questions very much like cookiecutter to let you choose lots of different deploy options (S3, rsync, Dropbox, etc), and generates a Makefile with the appropriate rules.

Refs:
* https://github.com/getpelican/pelican/blob/master/pelican/tools/pelican_quickstart.py
* https://github.com/getpelican/pelican/blob/master/pelican/tools/templates/Makefile.in

**Comment by jayqi** [comment]
Closing—implemented for V2.
