### ISSUE TITLE
Rename cookitcutter project

### ISSUE THREAD

**Issue by ManavalanG** [drivendata/cookiecutter-data-science#88]
Is it possible to properly rename a project created by cookiecutter? That is, besides renaming the directory, it should also properly edit file contents (eg. README.md) replacing old project name with new name. 

If there is not an automated-solution, is the below list of files inclusive of all files that need to be manually edited?
* README.md
* docs/index.rst
* docs/conf.py
* LICENSE

**Comment by pjbull** [comment]
There's not automated way, searching for `repo_name` and `project_name` are your best bet:

https://github.com/drivendata/cookiecutter-data-science/search?utf8=%E2%9C%93&q=%22cookiecutter.repo_name%22&type=

https://github.com/drivendata/cookiecutter-data-science/search?utf8=%E2%9C%93&q=%22cookiecutter.project_name%22&type=

**Comment by ManavalanG** [comment]
Thanks!
