### ISSUE TITLE
A Place for Predicted Data

### ISSUE THREAD

**Issue by JoshuaC3** [drivendata/cookiecutter-data-science#93]
I think there should be a specified place for predicted data. The reason for this is someone can quickly verify results.

Even with good structured setups, models like DNNs with hardware (GPU) dependencies can go wrong. We do not want to make someone setup tensorflow, torch, theano or keras to load a model and make predictions.

**Where should it go?**
1) In data in a new folder?
2) Models with the model that generated it?

**Comment by isms** [comment]
@JoshuaC3 how about `data/final/`?

**Comment by JoshuaC3** [comment]
I would have said `data/predictions` but looking at the READme it says it can be put in models. So maybe it would be good to have a `models/predictions` directory.

Does this sound reasonable?

**Comment by isms** [comment]
Sure. Does that close the issue or are you suggesting making this a default?

**Comment by JoshuaC3** [comment]
I would say have it as a default but it may not be necessary. If you think that it makes sense to include it then great, if not then I am happy to close this out.

**Comment by isms** [comment]
:+1:
