### ISSUE TITLE
Can you clarify what this project actually is?

### ISSUE THREAD

**Issue by matanster** [drivendata/cookiecutter-data-science#95]
Is this project more than a directory structure generator? 
If not, what functionality is included?

**Comment by willprice** [comment]
That's all it is, for use with the cookiecutter templating tool

**Comment by matanster** [comment]
Cool

**Comment by pjbull** [comment]
I'll close this for now, but if there were specific parts of the documentation that you think need an update, submit a PR or you can add them to this issue:
https://drivendata.github.io/cookiecutter-data-science/
