### ISSUE TITLE
Question/Request for documentation/Guidelines on how to best handle relative imports

### ISSUE THREAD

**Issue by TMorville** [drivendata/cookiecutter-data-science#99]
My question can be summarised shortly as: 

**What is the best way to handle relative import between submodules of `/src/`?** 

-----

This isn't really a issue, as much as a request for documentation or examples. Something that comes close to ["Request for a tutorial demonstrating simple implementation of cookie-cutter-data-science framework"](https://github.com/drivendata/cookiecutter-data-science/issues/59), however, the question is quite specific, and I think merits another tracker. 

 I have slightly changed the structure of my own cookie cutter implementation:

```
.
├── data
│   └── get_data.py
├── __init__.py
├── models
│   ├── predict_model.py
│   └── train_model.py
├── preprocessing
│   └── preprocessing.py
├── production
│   └── serve_model.py
└── visualization
    └── visualize.py
```

**How should relative imports be handled between different submodules?**

E.g. between train_model and preprocessing. A pseudo-example would be something like having two scripts `preprocessing.py`and `train_model.py`, where I want to call the former in the latter. 

```
import pandas as pd
import sklearn.preprocessing as preprocessing

class Preprocess:
    """A custom preprocessing pipeline that outputs test & training date
    """
    
    def apply_onehot(data):
    	return pd.get_dummies(data)

    def split_data(data):
    	return preprocessing.test_train_split(data)

```
```
from xgboost import XGBClassifier
from preprocessing import Preprocess

 class train_and_dump:
    """A custom training pipeline that trains & dumps a XGBoost model
    """
    
    def train(data):
    	X_train, X_test, y_train, y_test = Preprocess.split_data(data)

    	clf = XGBClassifier()

    	joblib.dump(clf)

```

How should I handle the relative import from `preprocessing/preprocessing.py` to `models/train_model`? 

I have tried various combinations, such as `from preprocessing import preprocessing` & `from src.preprocessing import preprocessing`with `__init.py__` files in each directory, and always standing in the main project folder running `python3 src/models/train_model.py`, as this would be where the `Makefile`would initiate `__main__`. 

However, none of this works and throws errors such as `from preprocessing.preprocessing import preprocessing`. It would be good to see if there is with a generic solution, before I look into different tools that allow me to do relative imports.  Perhaps I am missing something on how relative imports work, or where I should initiate `__main__`when calling a python script. 

Thanks!

**Comment by pjbull** [comment]
Hi @TMorville there's no simple generic solution as it depends on who the code gets called and what version of Python you're using. See this guide for a lot of the ins and outs:
https://chrisyeh96.github.io/2017/08/08/definitive-guide-python-imports.html

That said, we've got some work on #101 that should at least give a better example of this. I think that for your case I'm inclined to make the whole thing a package and use `from __future__ import absolute_import` for Python2 compatibility and then use absolute paths throughout. I think that's the most generic, but I'm open to other thoughts.

Closing this issue for now.
